
name: deploy

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 🛎️
      uses: actions/checkout@v3
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.2.2'
        bundler-cache: true
    - name: Update _config.yml ⚙️
      uses: fjogeleit/yaml-update-action@v0.13.1
      with:
        commitChange: true
        valueFile: '_config.yml'
        propertyPath: 'giscus.repo'
        value: ${{ github.repository }}
    - name: Install and Build 🔧
      run: |
    
    - name: Deploy 🚀
      if: github.event_name != 'pull_request'
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: _site

